<div class="ancho bg-negro">
	<div id="panel-slider" >
		<div id="slider-boton">
			<a href="#" class="f_atras"></a>
			<a href="#" class="f_adelante"></a>
		</div>
		<ul id="slider-puntero">
			<li><i></i></li>
			<li><i></i></li>
			<li><i></i></li>
			<li><i></i></li>
		</ul>
		<ul id="slider-imagen">
			<li><div id="slider-info">
				<div class="comentario">Mira cada Capitulo</div>
				<h3>Bleach</h3>
				<h4>Lorem Ipsum Dolor Set Amet text the printing and typesetting industry.</h4>
				<div><a href=""><i></i>Ver Completo</a></div>
				</div><img src="static.img/bleach_slide.jpg" />
			</li>
			<li><img src="static.img/anime2_slide.png" /></li>
			<li class="activo"><img src="static.img/anime3_slide.png" /></li>
			<li><img src="static.img/anime4_slide.png" /></li>
		</ul>
	</div>
</div>
<div class="ancho bg-gris">
	<div id="panel-secciones">
		<ul>
			<li class="ani">Animes</li>
			<li class="trl">Trailers</li>
			<li class="sug">Sugerido</li>
			<li class="mng">Manga</li>
			<li class="jms">JMusic</li>
		</ul>
		<div class="clear"></div>
	</div>
</div>
<div class="ancho bg-smoke"><!-- 100 -->
	<div id="panel-articulos" class="espp2x0"><!-- 96 -->
		<div class="sect-titulo">Más Buscados</div>
		<div><!-- 94 -->
			<div class="artic-content">
				<img src="static.img.ani/anime1.jpg" />
				<div class="artic-titulo espText">Hakkenden: touhou hakken ibun</div>
				<div class="artic-tiempo espText">Hace 2 min. <span>feb</span></div>
			</div>
			<div class="artic-content">
				<img src="static.img.ani/anime2.jpg" />
				<div class="artic-titulo espText">Hakkenden: touhou hakken ibun</div>
				<div class="artic-tiempo espText">Hace 2 min. <span>feb</span></div>
			</div>
			<div class="artic-content">
				<img src="static.img.ani/anime3.jpg" />
				<div class="artic-titulo espText">Hakkenden: touhou hakken ibun</div>
				<div class="artic-tiempo espText">Hace 2 min. <span>feb</span></div>
			</div>
			<div class="artic-content">
				<img src="static.img.ani/anime4.jpg" />
				<div class="artic-titulo espText">Hakkenden: touhou hakken ibun</div>
				<div class="artic-tiempo espText">Hace 2 min. <span>feb</span></div>
			</div>
		<div class="clear"></div>
		</div>
	</div>



</div>



<!--div class="ancho bg-smoke">
	<div id="panel-articulos" class="esp">
		<div class="sect-titulo">Más Buscados</div>
		<ul>
			<li>
				<div class="artic-content">
					<img src="static.img.ani/anime1.jpg" />
					<div class="artic-titulo espText">Hakkenden: touhou hakken ibun</div>
					<div class="artic-tiempo espText">Hace 2 min. <span>feb</span></div>
				</div>
				<div class="clear"></div>
			</li>
			<li>
				<div class="artic-content">
					<img src="static.img.ani/anime1.jpg" />
					<div class="artic-titulo espText">Hakkenden: touhou hakken ibun</div>
					<div class="artic-tiempo espText">Hace 2 min. <span>feb</span></div>
				</div>
				<div class="clear"></div>
			</li>
			<li>
				<div class="artic-content">
				<img src="static.img.ani/anime1.jpg" />
				<div class="artic-titulo espText">Hakkenden: touhou hakken ibun</div>
				<div class="artic-tiempo espText">Hace 2 min. <span>feb</span></div>
				</div>
				<div class="clear"></div>
			</li>
			<li>
				<div class="artic-content">
				<img src="static.img.ani/anime1.jpg" />
				<div class="artic-titulo espText">Hakkenden: touhou hakken ibun</div>
				<div class="artic-tiempo espText">Hace 2 min. <span>feb</span></div>
				</div>
				<div class="clear"></div>
			</li>
		</ul>
		<div class="clear"></div>
		<div class="sect-titulo">Animes Populares</div>
		<div class="clear"></div>
	</div>
	
</div-->