<!DOCTYPE html>
<html lang="es">
<head>
<meta charset="iso-8859-1" />
<title>OTAQUZ!</title>
<!--base href="http://www.otaquz.com/"/-->
<link rel="stylesheet" type="text/css" href="static.css/estilos.css" />
<script type="text/javascript" language="javascript" src="static.jsc/jquery-1.9.1.min.js" ></script>
</head>
<body>
<div class="ancho statico-top shadowt">
	<div class="marg">
		<div class="cabecera">
			<div id="logo"><i></i></div>
			<div id="busqueda">
				<input type="text" />
				<a href=""></a>
				<div id="busqueda_lista">
					<ul>
						<li>Todo</li>
						<li>Anime</li>
						<li>Generos</li>
						<li>Trailers</li>
						<li>Sugerido</li>
						<li>Manga</li>
						<li>JMusic</li>
					</ul>
				</div>
			</div>
			<div id="panel">
				<div class="bloque_usuario">
					<ul>
						<li>En Cola (<span class="usuario_cola">0</span>)</li>
						<li>Ajustes</li>
						<li><span>Yuri</span><img src="static.img/usr-9834h899uu.jpg" width="32" height="32" /></li>
					</ul>
				</div>
			</div>
		</div>
	</div>
</div>
<?php include __DIR_MODEL__."/contenedor.portada.phtml"; ?>
<div class="ancho">
	<div class="piepagina">
		<ul class="list-h list-izq">
			<li><a href="">Otaquz</a></li>
			<li><a href="">Blog</a></li>
			<li><a href="">Publicidad</a></li>
			<li><a href="">Trabajos</a></li>
			<li><a href="">Ayuda</a></li>
			<li><a href="">Sobre Nosotros</a></li>
		</ul>
		<ul class="list-h list-der">
			<li><a href="">Terminos de Uso</a></li>
			<li><a href="">Politica de Privacidad</a></li>
			<li><a href="">&copy; 2012 Otaquz</a></li>
		</ul>
	</div>
</div>
</body>
</html>